config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'

  get 'orders/show'

  get 'orders/new'

  root 'watches#index'
  resources :watches do 
  	resources :orders, only: [:index, :new, :create]
  end

  resources :users, except: [:index, :show] 
  get 'profile', to: 'users#show', as: :profile 
  resource :session

  # Receipt Page
  resources :orders, only: :show
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :watch
	belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :watches
	has_many :orders 

	validates :email, presence: true, uniqueness: { case_sensitive: false }

	before_create :sanitize_emails

	def sanitize_emails
		self.email = email.downcase 
	end

	def owns?(resource)
		self == resource.user 
	end

	def full_name
		"#{first_name} #{last_name}"
	end

	def name
		if first_name.present? 
			full_name
		else
			email
		end
	end
end

app/models/watch.rb
class Watch < ActiveRecord::Base
	belongs_to :user
	has_many :orders

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/	

  	validates :name, presence: true
  	validates :description, presence: true, length: {minimum: 20}
  	validates :user, presence: true 


	def price
		price_in_pence.to_f / 100
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :current_user_owns?	

  def current_user
  	if logged_in? 
  		# look for user with session info 
  		User.find(session[:user_id])
  	end
  end

  def logged_in?
  	session[:user_id].present?
  end

  def require_user 
    unless logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to new_session_path 
    end
  end

  def current_user_owns?(resource)
    current_user.present? and current_user.owns?(resource)
  end

  def require_owner(resource)
    unless current_user_owns?(resource)
      flash[:error] = "You must own the #{resource.class.to_s.downcase} to do that."
      redirect_to root_path 
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new
  	@order = Order.new
  end

  def create
  	@watch = Watch.find(params[:watch_id])
  	@order = @watch.orders.new(order_params)
  	@order.user = current_user

  end

  private
  def order_params
  	params.require(:order).permit(:stripe_token)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	# This can be blank 
  end

  def create
  	find_user 
  	if @user.present? and @user.authenticate(password)
  		# Log in here
  		log_in

  		redirect_home
  	else
  		re_render_form
  	end
  end

  def destroy 
  	# Log out	
  	reset_session 
  	flash[:success] = "See you again soon!"
  
  	redirect_to root_path
  end 

  private

  def find_user
    @user = User.find_by(email: email)
  end

  def log_in
  	reset_session
  	session[:user_id] = @user.id
  end

  def email
  	params[:session][:email]
  end

  def password
  	params[:session][:password]
  end

	def redirect_home
		flash[:success] = "Logged in!"
	  redirect_to root_path
	end  

	def re_render_form
		flash[:error] = "Oops, something went wrong. Please try again."
  	render :new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in
  	else
      re_render_form
  	end
  end

  def edit
  end


  private
  def user_params
  	params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def log_in
    #Prevent session hijacking
    reset_session
    # Log the user in 
    session[:user_id] = @user.id
    flash[:success] = "Thanks for signing up!"
    redirect_to root_path
  end

  def re_render_form
    flash[:error] = "Oops, something went wrong, please check the form for errors and try again."
    render :new
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :find_watch, except: [:index, :new, :create]
  before_action :require_user, only: [:new, :create]
  
  def index
  	# Pass an instance variable to the view 
  	@watches = Watch.all 
  	# Render the index view (Rails already doing this for us)
  end

  def show
    find_watch
  end

  def new
    @watch = Watch.new 
  end

  def create
    @watch = Watch.new(watch_params)
    if @watch.save
      flash[:success] = "Successfully uploaded #{@watch.name} to the store."
      redirect_to @watch
    else
      flash[:error] = "Please check the form for errors and try again."
      render :new
    end
  end

  def edit
    require_owner(@watch)
  end

  def update
    require_owner(@watch)
    if @watch.update(watch_params)
      flash[:success] = "#{@watch.name} successfully updated."
    else
      flash[:error] = "Please check the form for errors and try again."
      render :edit 
    end
  end

  def destroy 
    require_owner(@watch)
    if @watch.destroy
      flash[:success] = "#{@watch.name} was removed."
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private
  def watch_params
    params.require(:watch).permit(:name, :description, :price_in_pence, :brand, :gender, :style, :pre_owned, :image)
  end

  def find_watch
    @watch = Watch.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def payment_page?
		params[:controller] == "orders" and params[:action] == "new"
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timekeep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if payment_page? %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  
  <% end %>
</head>
<body data-stripe-pk="<%= Rails.application.secrets.stripe_pk %>">

<div class="container">
	<header>
		<nav>
			<%= link_to root_path do %>
				<h1>Time<br>Keep</h1>
			<% end %>

			<div class="actions">
				<% if logged_in?%>
					<%= link_to "Add Watch", new_watch_path %>
					<%= link_to current_user.name, profile_path %>
					<%= link_to "Log Out", session_path, method: :delete, class: "button" %>
				<% else %>
					<%= link_to "Log In", new_session_path %>
					<%= link_to "Sign Up", new_user_path, class: "button" %>
				<% end %>
			</div>
		</nav>

		<!-- Include User feddback code. -->
		<% flash.each do |key, value| %>
			<div class="flash <%= key %>">
				<p><%= value %></p>
			</div>
		<% end %>
	</header>

	<%= yield %>
</div>

<footer>
	<div class="container">
		<address>
			<p>Get In touch</p>
			<p>Exmouth House</p>
			<p>3 - 11 Pine Street</p>
		</address>

		<div>
			<a href="tel:+442071395252">+44 (0)20 7139 5252</a>
		</div>

		<div>
			<p><%= mail_to "hello@timekeep" %></p>
		</div>

		<div class="social">
			<%# social_link_to :facebook  %>
			<%# social_link_to :twitter  %>
		</div>
	</div>
</footer>

<script type="text/javascript">
  	// This identifies your website in the createToken call below
 		Stripe.setPublishableKey($('body').data('stripe-pk'));
  	// ...
</script>
</body>
</html>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<%= simple_form_for @order, url: watch_orders_path(params[:watch_id]) do |f|%>
	  <span class="payment-errors"></span>

	  <div class="form-row">
	    <label>
	      <span>Card Number</span>
	      <input type="text" size="20" data-stripe="number"/>
	    </label>
	  </div>

	  <div class="form-row">
	    <label>
	      <span>CVC</span>
	      <input type="text" size="4" data-stripe="cvc"/>
	    </label>
	  </div>

	  <div class="form-row">
	    <label>
	      <span>Expiration (MM/YYYY)</span>
	      <input type="text" size="2" data-stripe="exp-month"/>
	    </label>
	    <span> / </span>
	    <input type="text" size="4" data-stripe="exp-year"/>
	  </div>

	  <button type="submit">Submit Payment</button>
<% end %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :username %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>

	<%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<h1>User Settings</h1>
<%= render "form" %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render "form" %>

app/views/users/show.html.erb
<h1>Profile</h1>
<h2><%= current_user.name %></h2>

<!-- LIST ALL RECENT ORDERS -->


<!-- LIST ALL UPLOADED WATCHES -->
<% current_user.watches.each do |watch|  %>
	<h4><%= watch.name %></h4>
	<%= image_tag watch.image.url(:thumb) %>
	<p>Uploaded <%= time_ago_in_words watch.created_at %> ago.</p>
	<!-- # <p>< link_to "Purchased #{watch.orders.count}", watch_orders_path(watch) %> times.</p> -->
<% end %>
<!-- GROSS PROFIT ON WATCHES -->

app/views/watches/_form.html.erb
<%= simple_form_for @watch do|f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :price_in_pence %>
	<%= f.input :style %>
	<%= f.input :gender %>
	<%= f.input :pre_owned, as: :boolean, boolean_style: :inline, inline_label: "Pre-owned?" %>
	<%= f.input :brand %>
	<%= f.input :image %>

	<%= f.button :submit %>

<% end %>

app/views/watches/edit.html.erb
<h2>Edit <%= @watch.name %></h2>
<%= render "form" %>

app/views/watches/index.html.erb
<section class="watches">

	<% @watches.each do |watch| %>

		<div class="watch">
			<%= link_to watch do %>
				<!-- IMAGE -->
				<%= image_tag watch.image.url(:medium) %>
				<%= link_to "#" do %>
					<div class="price">
						<!-- PRICE -->
						<span>
							<%= number_to_currency watch.price, unit: "£"  %>
						</span>
					</div>
				<% end %>
			<% end %>

			<h2><%= watch[:name] %></h2>
		</div>

		

	<% end %>

</section>

app/views/watches/new.html.erb
<h2>New Watch</h2>
<%= render "form" %>

app/views/watches/show.html.erb
<section class="watch__large">
	<!-- IMAGE -->
	<%= image_tag @watch.image.url(:medium) %>
</section>

<section class="watch__info">
	<h2><%= @watch.name %></h2>
	<%= @watch.description %>

	<div>
		<span>Posted by <%= mail_to @watch.user.email, @watch.user.first_name %></span>
	</div>

	<div class="action">
		<% if current_user_owns?(@watch)  %>
			<%= link_to "Edit", edit_watch_path(@watch) %>
			<%= link_to "Delete", watch_path(@watch), method: :delete, class: "button" %>
		<% else  %>
			<b><%= number_to_currency @watch.price, unit: "£" %></b>
			<%= link_to "Buy", "#", class: "button" %>
		<% end %>
	</div>
</section>